### ISSUE TITLE
Error print(name) 

### ISSUE THREAD

**Issue by youpong** [nabetama/gimei#7]
Below code, [print_name.py](https://gist.github.com/youpong/23558fa9cbebf22b2dc29f30096164f7) doesn't work.

```python
from gimei import Gimei

name = Gimei().name
print(name)
```

Output
```
$ ./print_name.py
Traceback (most recent call last):
  File "./print_name.py", line 5, in <module>
    print(name)
TypeError: __str__ returned non-string (type bytes)
```

**Comment by nabetama** [comment]
@youpong Thanks, if you can write some code, I would be great if you could fix that bugs. I think it's probably around the character encoding.

**Comment by youpong** [comment]
I will make another pull request.  Please wait.

**Comment by youpong** [comment]
日本語で議論してもよろしいでしょうか？ 必要なら英語に戻します。

先程のエラーは、non-string が返却されることでおきています。 これは `__str__()` が `__repr__()` を呼び出しており、それが string ではなく byte 列を返しています。

ですので、この issue は解決すべき個別の２つのインシデントに分けられます。
- `__str__()` が期待される内容の文字列を返す。
- `__repr__()` が期待される内容の文字列を返す。 

前者は引き続き、この issue で議論しましょう。
後者の件は、新たに issue を起こしますのでそこで議論しましょう。順序としては `__repr__()` を先に解決しましょう。

**Comment by nabetama** [comment]
@youpong 手元でテストしたわけではないですが、`__str__()` を実装するで特に問題ないかと思ってました。
 `__repr__()` の実装は `eval()` に対応するように変更するほうが良いとは思いますが、正直あまりこだわりはありません。
当時  `__repr__()` で実装した理由はわかりませんが、プロパティを文字列で表現するのに楽とかその程度だと思います。
気軽に pull request 投げてくださいー

**Comment by youpong** [comment]
来週いっぱいバカンスに行ってしまうので、そのあとプルリクします。
間が空いてしまうのですが、よろしくお願いしますー。

**Comment by youpong** [comment]
PR#10 をマージした結果、上記 PR#11 がコンフリクトしてましたが、解決したのでご確認ください。

`__str__()` は、 `kanji()` と同じ値を返却するようにしました。
